### ISSUE TITLE
example usage of fmemory.findSignature

### ISSUE THREAD

**Issue by l3lackShark** [otvv/fmemory#1]
What's the current state of this function. Does it even work? If so, could you please provide a little example code?

**Comment by otvv** [comment]
The usage is pretty straight-forward:
```js
// find dummy function
const dummyFunction = fmemory.findSignature("\0xAA\0xAB\0xAC\0xAD\x00", "xxx?")
```
The function should be working as intended. I haven't tested it much, only on CS:GO.

**Comment by l3lackShark** [comment]
Does it default to the `ProcessID` when it comes to searching? This returns 0 to me, however, the signature is valid and unique.
![image](https://user-images.githubusercontent.com/20248967/80894735-327bb400-8cf7-11ea-8626-f23b2e0ab5a4.png)

**Comment by otvv** [comment]
Ah, I see whats wrong. I forgot to actually link the module to the sig-scanner :man_facepalming:. So you're pretty much reading nothing. For now you can use addresses instead of the signature.

```js
const unkAddress = 0xA072AC0

const dummyAddress = fmemory.readMem(moduleBaseAddress + unkAddress, fmemory.ULONG)
console.log(dummyAddress)

if (dummyAddress) {

  // do stuff
}
```
I'll start working on it, thanks for the feedback.

**Comment by l3lackShark** [comment]
Thanks for taking time on this. I was waiting and searching for a module like this for ages. Searching addresses won't work in my case since the game I'm trying to read from does not really have persist pointers. I will patiently wait for the fix. Please keep me updated.

**Comment by otvv** [comment]
Sure thing. I have done some more work on the sig-scanner here, but I can't test it properly right now. I could make a commit since it aggregates some other fixes for the library. It's not fully functional yet. (Something is wrong on the js end, since on C++ it works just fine.)
