### ISSUE TITLE
This as a standalone cpp library

### ISSUE THREAD

**Issue by l3lackShark** [otvv/fmemory#2]
Can you make this module as a standalone cpp library? This module seem to be (in the future when you will be done with this) the most advanced Linux memory reader. (apart from scanmem which is painfully slow) It would be cool to play around with.

**Comment by otvv** [comment]
I don't see a point on doing it right now, since there's a few of them already for C++. I recommend taking a look at this one: [trickster](https://github.com/neg4n/trickster). It's not as easy as mine, but it can do the trick just fine.

**Comment by l3lackShark** [comment]
I'm already using trickster. Found it on your stars list. And I'm not talking about right now, sorry, didn't make it clear. 

> (in the future when you will be done with this)
